### ISSUE TITLE
[Question] why default textDirection of `RubyTextData` is set to `rtl`?

### ISSUE THREAD

**Issue by narumi147** [YeungKC/RubyText#8]
In most cases and languages, left-to-right is used. So why right-to-left is used in this package?

In `RichText`, `textDirection` is default to null and check from context and there is no param in `TextSpan`.

**Comment by narumi147** [comment]
did you give up this package? (つД｀)･ﾟ･

**Comment by narumi147** [comment]
seems you wont work for this package

**Comment by YeungKC** [comment]
I'm sorry that I ignored some notifications from GitHub.

Set default textDirection cause by TextPainter.layout need a direction.
And use default direction from context now.
